version: "3.1"

services:
  db:
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-datavolume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-datavolume:
    driver: local
