default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: tudukeyo_development

test:
  <<: *default
  database: tudukeyo_test

production:
  <<: *default
  database: tudukeyo_production
  username: tudukeyo
  password: <%= ENV['TUDUKEYO_DATABASE_PASSWORD'] %>
